# Generated by Django 3.2.18 on 2023-05-22 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('descripcion', models.TextField(help_text='Describa las Propiedades de la categoría', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_socio', models.IntegerField()),
                ('nombre', models.CharField(max_length=2000, verbose_name='Nombre')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='Dni')),
                ('email', models.EmailField(max_length=150, null=True, verbose_name='Email')),
                ('te', models.CharField(max_length=100, verbose_name='Telefono')),
                ('activo', models.CharField(choices=[('V', 'Cliente VIP'), ('R', 'Regular'), ('N', 'No Compra')], max_length=1)),
                ('fecha_reg', models.DateField(blank=True, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('fecha_ultima_compra', models.DateField(blank=True, null=True)),
                ('fecha_ultimo_login', models.DateField(blank=True, null=True)),
                ('baja', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(help_text='Describa la planta', max_length=1000)),
                ('ambiente', models.CharField(choices=[('I', 'Interior'), ('E', 'Exterior'), ('C', 'Cualquiera')], max_length=1)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_producto', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('cod_categ', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField(help_text='Describa las Propiedades del Producto', max_length=1000)),
                ('precio', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('foto', models.ImageField(null=True, upload_to='foto_prod/', verbose_name='Foto Producto')),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publica.categoria')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publica.planta')),
            ],
        ),
        migrations.CreateModel(
            name='Kits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(help_text='Describa para que sirve el kit', max_length=1000)),
                ('accesorios', models.ManyToManyField(to='publica.Producto')),
            ],
        ),
    ]
